
services:

  rabbit:
    image: rabbitmq:3-management
    env_file:
      envs/.rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  fastapi:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0
    volumes:
      - .:/code
    ports:
      - '8000:8000'
    depends_on:
      rabbit:
        condition: service_started
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:15
    restart: unless-stopped
    user: postgres
    env_file:
      envs/.postgres
    volumes:
      - postgres-volume:/var/lib/postgresql/data
      - ./init-database.sh:/docker-entrypoint-initdb.d/init-database.sh

    ports:
      - '5432:5432'
      - '6543:5432'
    healthcheck:
       test: [ 'CMD', 'pg_isready' ]
       interval: 10s
       timeout: 5s
       retries: 5


volumes:
  postgres-volume:
